//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18408
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCPD_First_Response.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LCPD_First_Response.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;DATA&gt;
        ///&lt;BOAT CARPOS=-372.55, -1036.113, -0.1734731; CARHEADING=309.5673 /&gt;
        ///&lt;BOAT CARPOS=-425.0824, -979.6078, -0.009196341; CARHEADING=88.90623 /&gt;
        ///&lt;BOAT CARPOS=-419.9152, -941.471, -0.2630637; CARHEADING=359.7372 /&gt;
        ///&lt;BOAT CARPOS=-404.824, -941.8502, -0.2849999; CARHEADING=358.5869 /&gt;
        ///&lt;BOAT CARPOS=-333.7415, -915.0031, 0.1627063; CARHEADING=212.9089 /&gt;
        ///&lt;BOAT CARPOS=-240.8923, -908.6324, 0.001345873; CARHEADING=56.89823 /&gt;
        ///&lt;BOAT CARPOS=-234.0379, -1017.537, 0.002235919; CARHEADING=122.3478 /&gt;
        ///&lt;BOAT CA [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string boatpos {
            get {
                return ResourceManager.GetString("boatpos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die # ================================== Bohan ==================================
        ///1258.69384765625,1571.22717285156,16.4523487091064,265.1985;
        ///1328.25366210938,1518.07080078125,11.4727363586426,185.4126;
        ///1328.1513671875,1441.82214355469,11.4854125976563,179.0988;
        ///1329.00476074219,1405.36242675781,11.4659967422485,175.4848;
        ///1318.40795898438,1381.03015136719,11.4179992675781,94.39079;
        ///1285.48645019531,1387.45166015625,11.7055358886719,85.40276;
        ///1209.96130371094,1630.69348144531,16.1323184967041,32.30728;
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die # Ladies first
        ///AARON,ABBEY,ABBIE,ABBY,ABIGAIL,ADA,ADAH,ADALINE,ADAM,ADDIE,ADELA,ADELAIDA,ADELAIDE,ADELE,ADELIA,ADELINA,ADELINE,ADELL,ADELLA,ADELLE,ADENA,ADINA,ADRIA,ADRIAN,ADRIANA,ADRIANE,ADRIANNA,ADRIANNE,ADRIEN,ADRIENE,ADRIENNE,AFTON,AGATHA,AGNES,AGNUS,AGRIPINA,AGUEDA,AGUSTINA,AI,AIDA,AIDE,AIKO,AILEEN,AILENE,AIMEE,AISHA,AJA,AKIKO,AKILAH,ALAINA,ALAINE,ALANA,ALANE,ALANNA,ALAYNA,ALBA,ALBERT,ALBERTA,ALBERTHA,ALBERTINA,ALBERTINE,ALBINA,ALDA,ALEASE,ALECIA,ALEEN,ALEIDA,ALEISHA,ALEJANDRA,ALEJANDRINA,ALENA,ALENE, [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die # Contains a list of all police departments ingame with their positions
        ///# First position is the position of the blip to enter to the building the second is the position where your car will be choosen
        ///&lt;DATA&gt;
        ///&lt;PD BLIPPOS=93.5, 1212.0, 13.74; CARPOS=84.0, 1240.0, 14.5; CARHEADING=90 /&gt;
        ///&lt;PD BLIPPOS=48.0, 680.0, 13.5; CARPOS=54.0, 668.0, 13.5; CARHEADING=90 /&gt;
        ///&lt;PD BLIPPOS=212.11, -207.99, 9.76; CARPOS=266.75, -212.06, 5.56; CARHEADING=180 /&gt;
        ///&lt;PD BLIPPOS=992.0, 1876.0, 22.8; CARPOS=997.0, 1885.0, 22.8; CARH [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string PoliceDepartments {
            get {
                return ResourceManager.GetString("PoliceDepartments", resourceCulture);
            }
        }
    }
}
